language: ruby
cache: bundler
sudo: false
script: bundle exec rake travis
before_install:
 - gem update bundler
rvm:
- 1.9.3
- 2.2.0
- jruby-19mode
addons:
  code_climate:
    repo_token: 2feb9f7ee6d879b72c3b33fd897a801d7aa0eadcc72898242b5a2dff2435b937
deploy:
  provider: rubygems
  on:
    tags: true
  api_key:
    secure: XFUKxH18R6lT5In7phyVsL3a5mcESrssD2dlNrQvC2TXeBGif+0sSSt7ZfRuFve5XB0Wa8ruClFxRr0uMXRqUZUKc1/VbLM2DnLLkruK8pwdu2oQI3JMdcDtMmVsVxvJViAAy3ibuKuCTF2NbU+Yg/VrwMNU+aN63zsDR44t1IU=
